### ISSUE TITLE
Feature request : Alpha slider

### ISSUE THREAD

**Issue by X2Stone** [mmaletin/UnityColorPicker#1]
Hi,

Thanks a lot for your awesome color picker ! This is the most elegant I found !
Could it be possible to select a color with an alpha value ? Could you add an option to have an alpha slider ?
I would have loved to be able to add it myself but a I know nothing in shader programming...
Thanks a lot for your answer.

**Comment by mmaletin** [comment]
Hello. Glad you like it. I don't really have time to add features, but I don't think shader knowledge is required for this specific one. You can probably just use a standard unity slider underneath. If you want visuals to match, add a gradient texture to it that goes from black to white and tint it with a selected color. Won't be a single gameobject anymore, but should work just fine.
