### ISSUE TITLE
Multiple Color Pickers control each other

### ISSUE THREAD

**Issue by baroquedub** [mmaletin/UnityColorPicker#2]
Thank you for making this available. If you happen to still be working on it, can I ask how I might get multiple color pickers to work concurrently?

Currently if I have multiple pickers, then changing the color on one moves the controls on the other. They're in sync. The preview images work as expected. Only the correct one is changed.

**Comment by mmaletin** [comment]
I'm not currently working on it, but the fix is quite simple, so you should be able to do it yourself. Duplicate the original material, and assign the copy to the second color picker, and they won't be linked anymore. Hope it helps.

**Comment by mmaletin** [comment]
Alternatively you can delete the material from an image component on color pickers, and the materials will be created automatically in runtime.

**Comment by baroquedub** [comment]
Thank you. Helps a lot.
